name: Test Action
on: [pull_request]

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    name: Test out the action in this repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ github.token }}
          workflow: upload.yml
          name: benchmark_results
          path: old_benchmark
          commit: ${{github.event.pull_request.base.sha}}
        continue-on-error: true
      - name: Run the action
        uses: ./ # Uses an action in the root directory
        with:
          benchmark-file: "output.json"
          benchmark-metrics: 'name,max,min,mean,ops,rounds'
          comparison-benchmark-file: "old_benchmark/output.json"
